[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''
if self.hovering.target and self.hovering.target:is(Card) then
'''
position = "before"
payload = '''
do
	local isAd = controller.hovering.target and controller.hovering.target.config and controller.hovering.target.config.ad
	if isAd then
		if key == "r" then
		   G.FUNCS.remove_ad(controller.hovering.target.config.id)
		end
	end
end
'''
match_indent = true
