[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'after'
pattern = '''if self.ability.name == 'Gros Michel' then G.GAME.pool_flags.gros_michel_extinct = true end'''
payload = '''
if self.ability.name == 'Cavendish' then G.GAME.pool_flags.cavendish = true end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'engine/ui.lua'
position = 'before'
pattern = '''if self.config.colour and (self.config.colour[4] > 0.01) then'''
payload = '''
self.colour = self.colour or G.C.WHITE
'''
match_indent = true