[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
position = 'at'
pattern = '''
{n=G.UIT.R, config={align = "cm"}, nodes={
                {n=G.UIT.C, config={align = "cm", padding = 0.05, minw = 1.45*2 + spacing, minh = 1.15, colour = temp_col, emboss = 0.05, r = 0.1}, nodes={
                  {n=G.UIT.R, config={align = "cm"}, nodes={
                    {n=G.UIT.C, config={align = "cm", r = 0.1, minw = 1.28*2+spacing, minh = 1, colour = temp_col2}, nodes={
                      {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}},
                            scale_function = function ()
                                return scale_number(G.GAME.dollars, 2.2 * scale, 99999, 1000000)
                            end, maxw = 1.35, colours = {G.C.MONEY}, font = G.LANGUAGES['en-us'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}
                  }},
                  }},
                }},
            }},
'''
payload = '''
{n=G.UIT.R, config={align = "cm"}, nodes={
    {n=G.UIT.C, config={align = "cm"}, nodes={
                    {n=G.UIT.C, config={align = "cm", padding = 0.05, minw = 1.45 + spacing, minh = 1.15, colour = temp_col, emboss = 0.05, r = 0.1}, nodes={
                    {n=G.UIT.R, config={align = "cm"}, nodes={
                        {n=G.UIT.C, config={align = "cm", r = 0.1, minw = 1.28+spacing, minh = 1, colour = temp_col2}, nodes={
                        {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}},
                                scale_function = function ()
                                    return scale_number(G.GAME.dollars, 2.2 * scale, 10)
                                end, maxw = 1.35/2, colours = {G.C.MONEY}, font = G.LANGUAGES['en-us'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}
                    }},
                    }},
                    }},
                }},
    {n=G.UIT.C, config={minw = 0.05, padding = 0.05},nodes={}},
    {n=G.UIT.C, config={align = "cm"}, nodes={
                    {n=G.UIT.C, config={align = "cm", padding = 0.05, minw = 1.45 + spacing, minh = 1.15, colour = temp_col, emboss = 0.05, r = 0.1}, nodes={
                    {n=G.UIT.R, config={align = "cm"}, nodes={
                        {n=G.UIT.C, config={align = "cm", r = 0.1, minw = 1.28+spacing, minh = 1, colour = temp_col2}, nodes={
                        {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'cryptocurrency', prefix = '£'}, font = SMODS.Fonts['hpot_plincoin'],},
                                scale_function = function ()
                                    return scale_number(G.GAME.cryptocurrency, 2.2 * scale, 10)
                                end, maxw = 1.35/2, colours = {SMODS.Gradients.hpot_advert}, font = SMODS.Fonts['hpot_plincoin'], shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'crypto_text_UI'}}
                    }},
                    }},
                    }},
                }},
},
},
'''
match_indent = true           

[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'at'
pattern = '''
G.shop.alignment.offset.y = -5.3
G.shop.alignment.offset.x = 0
'''
payload = '''
G.shop.alignment.offset.y = -5.9
G.shop.alignment.offset.x = 0
'''
match_indent = true

