[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
position = 'at'
pattern = '''        for k, card in ipairs(self.cards) do
            if not card.states.drag.is then '''
payload = '''        for k, card in ipairs(self.cards) do
            if (not card.states.drag.is) or card == G.lock_in_card then '''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'before'
pattern = '''    if self.CONTROLLER.focused.target and getmetatable(self.CONTROLLER.focused.target) == Card and'''
payload = '''    if G.draw_lockin_background and G.lock_in_card then
        local card = G.lock_in_card
        card.states.visible = true
        local r, g, b, a = love.graphics.getColor()
        love.graphics.setColor(0, 0, 0, 0.33)
        love.graphics.rectangle("fill", -100, -100, 100000, 100000)
        love.graphics.setColor(r, g, b, a)
    end'''
match_indent = true