[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
position = 'before'
pattern = '''
for k, card in pairs(self.cards) do
'''
payload = '''
self.cards = self.cards or {}
'''
match_indent = true


[[patches]]
[patches.pattern]
target = 'engine/ui.lua'
position = 'at'
pattern = '''
if self.UIT == G.UIT.O and not self.config.no_role then
    self.config.object:set_role(self.config.role or {role_type = 'Minor', major = self, xy_bond = 'Strong', wh_bond = 'Weak', scale_bond = 'Weak'})
end
'''
payload = '''
if self.UIT == G.UIT.O and not self.config.no_role and self.config.object then
    self.config.object:set_role(self.config.role or {role_type = 'Minor', major = self, xy_bond = 'Strong', wh_bond = 'Weak', scale_bond = 'Weak'})
end
'''
match_indent = true

