[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Game:draw
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''timer_checkpoint('uiboxes', 'draw')'''
payload = '''
if self.STATE == self.STATES.NURSERY then
  PlinkoGame.f.draw()
end

'''
match_indent = true


# Stop shop from re-appearing after consumable was used
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'before'
pattern = '''
G.shop.alignment.offset.y = G.shop.alignment.offset.py'''
payload = '''
if G.STATE ~= G.STATES.NURSERY then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'after'
pattern = '''
G.shop.alignment.offset.py = nil'''
payload = '''
end
'''
match_indent = true