[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''self.GAME = saveTable and saveTable.GAME or self:init_game_object()'''
payload = '''
init_jtem(self.GAME)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''globals.lua'''
position = 'at'
pattern = '''VERSION = '1.0.1o'
VERSION = VERSION..'-FULL'
'''
payload = '''VERSION = '1.0.1o'
VERSION = VERSION..'-H0TP0T'
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'before'
pattern = '''if self.STATE == self.STATES.PLAY_TAROT then'''
payload = '''
if self.STATE == self.STATES.JTEM_PANDEMONIUM then
  PandemoniumGame.f.update(dt)
end

'''
match_indent = true

# Game:draw
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''timer_checkpoint('uiboxes', 'draw')'''
payload = '''
if self.STATE == self.STATES.JTEM_PANDEMONIUM then
  PandemoniumGame.f.draw()
end

'''
match_indent = true

# I am so frustrated
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
position = 'at'
pattern = '''if G.GAME.blind then t[#t + 1] = { object = G.GAME.blind, scored_card = G.GAME.blind.children.animatedSprite } end'''
payload = '''if G.GAME.blind and G.GAME.blind.is and G.GAME.blind:is(Blind) then t[#t + 1] = { object = G.GAME.blind, scored_card = G.GAME.blind.children.animatedSprite } end'''
match_indent = true

# Draggable UIBoxes
[[patches]]
[patches.pattern]
target = 'engine/ui.lua'
position = 'before'
pattern = '''if args.config.can_collide == nil then '''
payload = '''
if args.config.draggable then
  self.states.drag.can = true
end
'''
match_indent = true

# Jukebox music is prioritized
[[patches]]
[patches.pattern]
target = '''functions/misc_functions.lua'''
pattern = '''if G.F_SOUND_THREAD then
    G.SOUND_MANAGER.channel:push(G.ARGS.push)'''
position = 'before'
payload = '''
if JTJukebox.CurrentlyPlaying and JTJukebox.ActuallyPlaying then
	desired_track = JTJukebox.ActuallyPlaying
	G.ARGS.push.desired_track = desired_track
end
'''
match_indent = true


# make the hook hook properly i hope
[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''    if self.area then self.area:remove_card(self) end'''
position = 'before'
payload = '''
self.hp_area_back = self.area
'''
match_indent = true
[[patches]]
[patches.pattern]
target = '''card.lua'''
pattern = '''        if self.ability.d_size > 0 then
            G.GAME.round_resets.discards = G.GAME.round_resets.discards - self.ability.d_size'''
position = 'before'
payload = '''
if self.hp_area_back and not self.hp_area_back.REMOVED then
    SMODS.calculate_context{ hp_card_destroyed = true, card_being_destroyed = self, is_being_sold = self.HP_JTEM_IS_BEING_SOLD, area = self.hp_area_back }
end
'''
match_indent = true