[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''self.GAME = saveTable and saveTable.GAME or self:init_game_object()'''
payload = '''
init_jtem(self.GAME)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''globals.lua'''
position = 'at'
pattern = '''VERSION = '1.0.1o'
VERSION = VERSION..'-FULL'
'''
payload = '''VERSION = '1.O.1o'
VERSION = VERSION..'-empty'
'''
match_indent = true