[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '''engine/text.lua'''
pattern = '''if old_string ~= new_string or first_pass then'''
position = "before"
payload = '''
self.strings[k].font = self.config.string[k].font or self.config.font or G.LANG.font
self.font = self.config.string[k].font or self.config.font or G.LANG.font
'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''engine/text.lua'''
pattern = '''if self.children.particle_effect then self.children.particle_effect:draw() end'''
position = "after"
payload = '''
self.font = self.strings[self.focused_string].font or self.config.font or G.LANG.font
self.text_offset = {
    x = self.font.TEXT_OFFSET.x*self.scale + (self.config.x_offset or 0),
    y = self.font.TEXT_OFFSET.y*self.scale + (self.config.y_offset or 0),
}
'''
match_indent = true
