[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

#dummy
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/ui.lua"]'
position = 'after'
pattern = '''
string that misses
'''
payload = '''
'''
match_indent = true

# [[patches]]
# [patches.pattern]
# target = '=[SMODS _ "src/ui.lua"]'
# position = 'after'
# pattern = '''
# if has_other_gameobjects then
#     rightside_nodes[#rightside_nodes+1] = UIBox_button({button = 'your_collection_other_gameobjects', label = {localize('k_other')}, minw = 5, id = 'your_collection_other_gameobjects', focus_args = {snap_to = true}})
# end
# '''
# payload = '''
# if G.ACTIVE_MOD_UI.id == 'HotPotato' then
#     leftside_nodes[#leftside_nodes + 1] = UIBox_button({button = 'your_collection_teams', label = {localize('k_teams')}, minw = 5})
# end
# '''
# match_indent = true
