[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# plincoins will be real in 2013
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''bankrupt_at = 0,'''
payload = '''
plincoins = 0,
balls_dropped = 0,
'''
match_indent = true

# make the czech colour
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
position = 'after'
pattern = '''spectral = G.C.SECONDARY_SET.Spectral,'''
payload = '''hpot_czech = HEX("D2B48C"),'''
match_indent = true

# czech pack colours 1/3
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'after'
pattern = '''ease_colour(G.C.DYN_UI.MAIN, mix_colours(G.C.SECONDARY_SET.Spectral, G.C.BLACK, 0.9))'''
payload = '''elseif state == G.STATES.CZECH_PACK then 
    ease_colour(G.C.DYN_UI.MAIN, mix_colours(HEX("D2B48C"), G.C.BLACK, 0.9))'''
match_indent = true

# czech pack colours 2/3
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'after'
pattern = '''ease_background_colour{new_colour = G.C.SECONDARY_SET.Spectral, special_colour = darken(G.C.BLACK, 0.2), contrast = 2}'''
payload = '''elseif state == G.STATES.CZECH_PACK then 
    ease_background_colour{new_colour = darken(G.C.GREEN, 0.2), special_colour = G.C.GREEN, contrast = 5}'''
match_indent = true

# czech pack colours 3/3
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'after'
pattern = '''G.STATE = G.STATES.BUFFOON_PACK'''
payload = '''   G.GAME.pack_size = self.ability.extra
elseif card.kind == 'hpot_czech' then
    G.STATE = G.STATES.CZECH_PACK'''
match_indent = true