[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# empty patches to copypaste later 
# I'm lazy okay?
[[patches]]
[patches.pattern]
target = 'card.lua'
position = 'before'
pattern = '''unreal patch'''
payload = '''
1000000 million dollar'''
match_indent = true


[[patches]]
[patches.regex]
target = 'card.lua'
position = 'after'
pattern = '''
very real patch'''
payload = '''
abab'''

# Game:update
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'before'
pattern = '''if self.STATE == self.STATES.PLAY_TAROT then'''
payload = '''
if self.STATE == self.STATES.PLINKO then
  update_plinko(dt)
end

'''
match_indent = true

# Game:draw
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''timer_checkpoint('uiboxes', 'draw')'''
payload = '''
if self.STATE == self.STATES.PLINKO then
  PlinkoGame.f.draw()
end

'''
match_indent = true

# Game:draw
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
position = 'after'
pattern = '''(self.config.type == 'hand' and state == G.STATES.SMODS_BOOSTER_OPENED) or'''
payload = '''
(self.config.type == 'hand' and G.STATE == G.STATES.PLINKO) or'''
match_indent = true

# ease_background_colour_blind
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
position = 'before'
pattern = '''elseif state == G.STATES.TAROT_PACK then'''
payload = '''
elseif state == G.STATES.PLINKO then
    ease_colour(G.C.DYN_UI.MAIN, mix_colours(G.C.MONEY, G.C.BLACK, 0.9))
'''
match_indent = true

# TEMPORARY PATCH (probably not temporary)
# some fuckery happens when loading back into run while quit during plinko
# save_run
[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
position = 'at'
pattern = '''STATE = G.STATE,'''
payload = '''
STATE = G.STATE == G.STATES.PLINKO and G.STATES.SHOP or G.STATE,
'''
match_indent = true

# Remove plinko when closing the run and what not
[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''if self.shop then self.shop:remove(); self.shop = nil end'''
payload = '''
if self.plinko then self.plinko:remove(); self.plinko = nil end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'after'
pattern = '''G.shop = nil'''
payload = '''
if G.plinko_rewards then
  G.plinko_rewards:remove()
  G.plinko_rewards = nil
end
if G.plinko then
  G.plinko:remove()
  G.plinko = nil
end
'''
match_indent = true

# Stop shop from re-appearing after consumable was used
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'before'
pattern = '''
G.shop.alignment.offset.y = G.shop.alignment.offset.py'''
payload = '''
if G.STATE ~= G.STATES.PLINKO then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'after'
pattern = '''
G.shop.alignment.offset.py = nil'''
payload = '''
end
'''
match_indent = true

# Add plincoins on cashout
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
position = 'before'
pattern = '''
add_round_eval_row({name = 'bottom', dollars = dollars})'''
payload = '''
if G.GAME.plincoins_per_round and G.GAME.plincoins_per_round > 0 then
  -- Add Plincoins
  add_round_eval_plincoins({name='plincoins', pitch = pitch, plincoins = G.GAME.plincoins_per_round})
end

'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'after'
pattern = '''
ease_dollars(G.GAME.current_round.dollars)'''
payload = '''
--
ease_plincoins(G.GAME.current_round.plincoins)
G.GAME.current_round.plincoins = 0
--
'''
match_indent = true

