[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Add plincoins on cashout
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
position = 'before'
pattern = '''
add_round_eval_row({name = 'bottom', dollars = dollars})'''
payload = '''
    for _, area in ipairs(SMODS.get_card_areas('jokers')) do
            for _, _card in ipairs(area.cards) do
            local ret = _card:calculate_plincoin_bonus()
    
            -- TARGET: calc_dollar_bonus per card
            if ret then
                i = i+1
                add_round_eval_plincoins({name='plincoins', plincoins = ret, bonus = true, name='joker'..i, pitch = pitch, card = _card})
                pitch = pitch + 0.06
                dollars = dollars + ret
            end
        end
    end
'''
match_indent = true