[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'game.lua'
position = 'after'
pattern = '''self.GAME.selected_back_key = selected_back'''
payload = '''
init_sillyposting(self.GAME)
'''
match_indent = true