[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add credits on cashout / thank you to whoever added the cashout stuff :sob:

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
position = 'after'
pattern = '''
ease_dollars(G.GAME.current_round.dollars)'''
payload = '''
--
    if G.GAME.current_round.credits and G.GAME.current_round.credits > 0 then
      HPTN.ease_credits(G.GAME.current_round.credits) 
      G.GAME.current_round.credits = 0
    end
--
'''
match_indent = true


[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
position = 'at'
pattern = "add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})"
payload = '''
if G.GAME.modifiers.interest_to_credits then
  add_round_eval_credits({name='credits', pitch = pitch, credits = ((G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)) * 2)})
else
  add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})
end

'''
match_indent = true


