[manifest]
version = "1.0.0"
dump_lua = true
priority = 1


[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''  elseif card.area and card.area == G.pack_cards then'''
position = 'before'
payload = '''
  elseif string.find(card.config.center.key, "iris") and (card.area and card.area == G.pack_cards) then
     return {
      n=G.UIT.ROOT, config = {padding = 0, colour = G.C.CLEAR}, nodes={
        {n=G.UIT.R, config={ref_table = card, r = 0.08, padding = 0.1, align = "bm", minw = 0.5*card.T.w - 0.15, maxw = 0.9*card.T.w - 0.15, minh = 0.3*card.T.h, hover = true, shadow = true, colour = G.C.UI.BACKGROUND_INACTIVE, one_press = true, button = 'pull_card', func = 'can_pull_card'}, nodes={
          {n=G.UIT.T, config={text = localize('b_select'),colour = G.C.UI.TEXT_LIGHT, scale = 0.45, shadow = true}}
        }},
    }}
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''  if card.ability.consumeable then
    if (card.area == G.pack_cards and G.pack_cards) then'''
position = 'at'
payload = '''
  if card.ability.consumeable and not string.find(card.config.center.key, "iris") then
    if (card.area == G.pack_cards and G.pack_cards) then
'''
match_indent = false
times = 1