[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
    contents.dollars_chips = {n=G.UIT.R, config={align = "cm",r=0.1, padding = 0,colour = G.C.DYN_UI.BOSS_MAIN, emboss = 0.05, id = 'row_dollars_chips'}, nodes={
      {n=G.UIT.C, config={align = "cm", padding = 0.1}, nodes={
        {n=G.UIT.C, config={align = "cm", minw = 1.3}, nodes={
          {n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.3}, nodes={
            {n=G.UIT.T, config={text = localize('k_round'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
          }},
          {n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.3}, nodes={
            {n=G.UIT.T, config={text =localize('k_lower_score'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
          }}
        }},
        {n=G.UIT.C, config={align = "cm", minw = 3.3, minh = 0.7, r = 0.1, colour = G.C.DYN_UI.BOSS_DARK}, nodes={
          {n=G.UIT.O, config={w=0.5,h=0.5 , object = stake_sprite, hover = true, can_collide = false}},
          {n=G.UIT.B, config={w=0.1,h=0.1}},
          {n=G.UIT.T, config={ref_table = G.GAME, ref_value = 'chips_text', lang = G.LANGUAGES['en-us'], scale = 0.85, colour = G.C.WHITE, id = 'chip_UI_count', func = 'chip_UI_set', shadow = true}}
        }}
      }}
    }}
'''
position = "at"
payload = '''
    contents.dollars_chips = {n=G.UIT.R, config={align = "cm",r=0.1, padding = 0,colour = G.C.DYN_UI.BOSS_MAIN, emboss = 0.05, id = 'row_dollars_chips'}, nodes={
      {n=G.UIT.C, config={align = "cm", padding = 0.1}, nodes={
        
        -- Credits tab

        {n=G.UIT.C, config={align = "cm", minw = 1.3}, nodes={
          {n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.3}, nodes={
            {n=G.UIT.T, config={text = localize('hpot_credit_text'), scale = 0.25, colour = G.C.BLUE, shadow = true}}
          }},
          {n=G.UIT.R, config={minh = spacing},nodes={}},
          {n=G.UIT.R, config={align = "cm", minh = 0.7}, nodes={
            {n=G.UIT.C, config={align = "cm", r = 0.1, minw = 0.64*2+spacing, minh = 0.7, colour = temp_col2}, nodes={
              {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'credits_text', prefix = ''}}, maxw = 1.35, colours = {G.C.BLUE}, font = G.LANGUAGES['en-us'].font, shadow = true,spacing = 2, bump = true, scale = 1.6*scale}), id = 'credits_UI_text'}}
            }},
          }},
        }},

        -- Chips tab

        {n=G.UIT.C, config={align = "cm", minw = 1.3}, nodes={
          {n=G.UIT.R, config={align = "cm", padding = 0, maxw = 1.3}, nodes={
              {n=G.UIT.T, config={text = (localize('k_round') .. " " .. localize('k_lower_score')), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
          }},
          {n=G.UIT.R, config={minh = spacing},nodes={}},
          {n=G.UIT.R, config={align = "cm", minh = 0.7}, nodes={
            {n=G.UIT.C, config={align = "cm", r = 0.1, minw = 3.3, minh = 0.7, colour = temp_col2}, nodes={
              {n=G.UIT.O, config={w=0.5,h=0.5 , object = stake_sprite, hover = true, can_collide = false}},
              {n=G.UIT.B, config={w=0.1,h=0.1}},
              {n=G.UIT.T, config={ref_table = G.GAME, ref_value = 'chips_text', lang = G.LANGUAGES['en-us'], scale = 0.42, colour = G.C.WHITE, id = 'chip_UI_count', func = 'chip_UI_set', shadow = true}}
            }},
          }},
        }},

        -- ref
        --[[
        {n = G.UIT.C, config = {padding = 0, minw = 1.3}, nodes = {
          {n = G.UIT.R, config = {align = "cm", padding = 0}, nodes = {
            {n=G.UIT.C, config={align = "cm", padding = 0, maxw = 1.3}, nodes={
              {n=G.UIT.T, config={text = (localize('k_round') .. " " .. localize('k_lower_score')), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}
            }},
          }},
          {n=G.UIT.R, config={minh = spacing},nodes={}},
          {n = G.UIT.R, config = {align = "cm"}, nodes = {
            {n=G.UIT.C, config={align = "cm", minw = 3.3, minh = 0.7, r = 0.1, colour = G.C.DYN_UI.BOSS_DARK, padding = 0}, nodes={
              {n=G.UIT.O, config={w=0.5,h=0.5 , object = stake_sprite, hover = true, can_collide = false}},
              {n=G.UIT.B, config={w=0.1,h=0.1}},
              {n=G.UIT.T, config={ref_table = G.GAME, ref_value = 'chips_text', lang = G.LANGUAGES['en-us'], scale = 0.42, colour = G.C.WHITE, id = 'chip_UI_count', func = 'chip_UI_set', shadow = true}}
            }}
          }}
        }}
        ]]
      }}
    }}
'''
match_indent = false
